#!/usr/bin/env python

# cvifier: the CV transmogrifier
# Copyright (C) 2013 Erik Tollerud
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import division

import sys
import argparse

from cvifier import core

parser = argparse.ArgumentParser()

parser.add_argument('contentfile', help='The file with the ReST actual content for this CV, or "stdin" to use standard input.')
parser.add_argument('writer', help='The writer to use. ')
parser.add_argument('-o', '--outfile', help='The output file.  Default is to use stdout', default=sys.stdout)
parser.add_argument('-s', '--settingsfile', help='The file with the settings for this writer. Default assumes the {writername}.cvsettings convention.', default=None)

args = parser.parse_args()

if args.contentfile == 'stdin':
    content = sys.stdin.read()
else:
    content = args.contentfile

core.main(content, args.writer, args.outfile, args.settingsfile)